### ISSUE TITLE
Analogico do gamepad so esta fornecendo valores redondos

### ISSUE THREAD

**Issue by BarbaraAlmeida** [UFMG-Autobotz/Autobotz-user-interface#5]
Testei o gamepad com o joystick da sede e no analógico só esta enviando velocidades das rodas inteiras, as mesmas dos botões, era pra isso acontecer mesmo @vcastromg ?

**Comment by vcastromg** [comment]
Não é bug, o analógico do joystick da sede deve ser ativado apertando o botão ANALOG. A luz vermelha acima do botão se acenderá indicando.

**Comment by BarbaraAlmeida** [comment]
Deu certo, obrigada.
